Add controllers
vladbakushkin/java-shareit pull request #1
Opened 2024-04-26 19:25 UTC by vladbakushkin

1. Реализованы модели данных User, Item
2. Созданы DTO-объекты и мапперы User, Item
3. Разработаны контроллеры для User, Item

## API для Item

### Добавление новой вещи
`POST /items.`

На вход поступает объект `ItemDto`. 
`userId` в заголовке `X-Sharer-User-Id` — это идентификатор пользователя, который добавляет вещь. Именно этот пользователь — владелец вещи.

### Редактирование вещи
`PATCH /items/{itemId}`

Изменить можно название, описание и статус доступа к аренде. Редактировать вещь может только её владелец.
`userId` в заголовке `X-Sharer-User-Id` — это идентификатор пользователя, который обновляет вещь. Именно этот пользователь — владелец вещи.

### Просмотр информации о конкретной вещи по её идентификатору
`GET /items/{itemId}`

Информацию о вещи может просмотреть любой пользователь.

### Просмотр владельцем списка всех его вещей с указанием названия и описания для каждой.
`GET /items`

`userId` в заголовке `X-Sharer-User-Id` — это идентификатор пользователя, который добавляет вещь. Именно этот пользователь — владелец вещи.

### Поиск вещи потенциальным арендатором. 
`GET /items/search?text={text}`

Пользователь передаёт в строке запроса текст, и система ищет вещи, содержащие этот текст в названии или описании.  В text передаётся текст для поиска. Возвращаются только доступные для аренды вещи.

2024-04-27 14:04 UTC, LexLippi requested changes
Привет!

Отличная работа!

Есть одно небольшое замечание, которое можно исправить!

Желаю удачи!

2024-04-27 14:04 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +        }
Лучше в такой ситуации использовать метод `ifPresent(foundUser -> ...)`

2024-04-28 08:46 UTC, vladbakushkin commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +        }
Переписал с использованием ifPresent

2024-04-28 18:56 UTC, LexLippi commented
Привет!

Отличная работа!

Желаю удачи в следующих спринтах!

2024-04-28 19:45 UTC, merged