Add bookings
vladbakushkin/java-shareit pull request #2
Opened 2024-05-18 11:03 UTC by vladbakushkin

### Добавлено взаимодействие приложения с БД.

### Реализована функция бронирования.
- Добавление нового запроса на бронирование.
Эндпоинт — `POST /bookings`
- Подтверждение или отклонение запроса на бронирование.
Эндпоинт — `PATCH /bookings/{bookingId}?approved={approved}`
- Получение данных о конкретном бронировании (включая его статус).
Эндпоинт — `GET /bookings/{bookingId}`
- Получение списка всех бронирований текущего пользователя. 
Эндпоинт — `GET /bookings?state={state}`
- Получение списка бронирований для всех вещей текущего пользователя. 
Эндпоинт — `GET /bookings/owner?state={state}`

### Добавлены даты бронирования при просмотре вещей.

Теперь владелец может увидеть даты последнего и ближайшего следующего бронирования для каждой вещи, когда просматривает список (`GET /items`) или конкретную вещь (`GET /items/{itemId}`).

### Добавлена возможность оставлять отзывы.
Комментарий можно добавить по эндпоинту `POST /items/{itemId}/comment`.

2024-05-19 20:47 UTC, LexLippi requested changes
Привет!

Хорошая работа!

Есть некоторое количество замечаний, которые необходимо исправить!

Желаю удачи!

2024-05-19 20:47 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> +    public BookingResponseDto addBooking(@RequestHeader("X-Sharer-User-Id") Long userId,
Строку `"X-Sharer-User-Id"` можно вынести в константу проекта

2024-05-19 20:47 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/booking/dto/BookingDtoMapper.java
> +@RequiredArgsConstructor
Зачем эта аннотация, если у класса нет полей?

2024-05-19 20:47 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/booking/dto/BookingDtoMapper.java
> +@Component
Вообще это не компонент, а в чистом виде `UtilityClass`

https://www.baeldung.com/java-helper-vs-utility-classes

2024-05-19 20:47 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +            }
Всегда советую по возможности сокращать уровень вложенности для читаемости кода:

```java
if (approved && booking.getStatus() == BookingStatus.APPROVED) {
    throw new BadRequestException("Booking with id = " + bookingId + " is already approved");
}

booking.setStatus(approved ? BookingStatus.APPROVED : BookingStatus.REJECTED);
```

2024-05-19 20:47 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/item/dto/CommentDtoMapper.java
> +@Component
Про это писал уже

2024-05-19 20:47 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +                .filter(b -> b.getEnd().isBefore(LocalDateTime.now()))
лучше через `&&` связать, а не использовать два фильтра подряд

это касается всех фильтров в классе

2024-05-19 20:47 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/user/dto/UserDtoMapper.java
> +@Component
Про это писал уже

2024-05-20 17:16 UTC, vsbakushkin commented on src/main/java/ru/practicum/shareit/booking/dto/BookingDtoMapper.java
> +@RequiredArgsConstructor
Видимо, осталась от изменений в предыдущих коммитах.
Исправил.

2024-05-20 17:29 UTC, vladbakushkin commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +            }
Согласен, исправил.

2024-05-20 17:56 UTC, vladbakushkin commented on src/main/java/ru/practicum/shareit/booking/dto/BookingDtoMapper.java
> +@Component
Исправил

2024-05-20 18:00 UTC, vladbakushkin commented on src/main/java/ru/practicum/shareit/item/dto/CommentDtoMapper.java
> +@Component
Исправил

2024-05-20 18:01 UTC, vladbakushkin commented on src/main/java/ru/practicum/shareit/user/dto/UserDtoMapper.java
> +@Component
Исправил

2024-05-20 18:15 UTC, vladbakushkin commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +                .filter(b -> b.getEnd().isBefore(LocalDateTime.now()))
Изначально была мысль переделать в одно большое условие, но показалось, что через несколько фильтров код получится более читаемым и не повлияет сильно на производительность.

Исправил.

2024-05-20 19:09 UTC, vladbakushkin commented on src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> +    public BookingResponseDto addBooking(@RequestHeader("X-Sharer-User-Id") Long userId,
Сделал

2024-05-21 06:39 UTC, LexLippi commented
Привет!

Отличная работа!

Желаю удачи в следующих спринтах!

2024-05-21 16:54 UTC, merged