Add item requests
vladbakushkin/java-shareit pull request #3
Opened 2024-05-30 19:51 UTC by vladbakushkin

- Добавлена функция запроса вещи

- Добавлена функция ответа на запрос

- Добавлена пагинация к существующим эндпоинтам

- Добавлены тесты

2024-05-31 20:18 UTC, LexLippi requested changes
Привет!

Хорошая работа!

Есть некоторое количество замечаний, которые необходимо исправить!

Желаю удачи!

2024-05-31 20:18 UTC, LexLippi commented on src/test/java/ru/practicum/shareit/user/service/UserServiceIntegrationTest.java
> +public class UserServiceIntegrationTest {
В тестах нет необходимости в модификаторах доступа

2024-05-31 20:18 UTC, LexLippi commented on src/test/java/ru/practicum/shareit/user/service/UserServiceImplTest.java
> +    }
Сценарии, которые с внешней стороны не отличаются друг от друга (даже несмотря на разные проверки внутри) можно объединять в один тест-кейс

2024-05-31 20:18 UTC, LexLippi commented on src/test/java/ru/practicum/shareit/item/repository/ItemRepositoryTest.java
> +    }
Зачем тебе пустые тесты?

Что они проверяют?

2024-05-31 20:18 UTC, LexLippi commented on src/test/java/ru/practicum/shareit/item/repository/CommentRepositoryTest.java
> +}
Зачем нам пустой тест класс?

2024-05-31 20:18 UTC, LexLippi commented on src/test/java/ru/practicum/shareit/booking/repository/BookingRepositoryTest.java
> +}
Это выглядит очень странно

2024-05-31 21:06 UTC, vladbakushkin commented on src/test/java/ru/practicum/shareit/user/service/UserServiceIntegrationTest.java
> +public class UserServiceIntegrationTest {
При создании класса он ставится по умолчанию, я даже и не думал, что нужно удалять.
Исправил

2024-05-31 21:06 UTC, vladbakushkin commented on src/test/java/ru/practicum/shareit/user/service/UserServiceImplTest.java
> +    }
Объединил несколько тестов в один

2024-05-31 21:07 UTC, vladbakushkin commented on src/test/java/ru/practicum/shareit/item/repository/ItemRepositoryTest.java
> +    }
В вебинаре рассказывали, что даже без добавления какой либо реализации в тестовые методы, при поднятии контекста пройдут проверки на корректность написания запросных методов и sql-запросов (@Query). Поэтому решил их оставить. Если смысла в этом никакого нет, то могу удалить.

2024-05-31 21:07 UTC, vladbakushkin commented on src/test/java/ru/practicum/shareit/item/repository/CommentRepositoryTest.java
> +}
Ответил выше

2024-05-31 21:07 UTC, vladbakushkin commented on src/test/java/ru/practicum/shareit/booking/repository/BookingRepositoryTest.java
> +}
Ответил выше

2024-06-01 07:57 UTC, LexLippi commented on src/test/java/ru/practicum/shareit/item/repository/ItemRepositoryTest.java
> +    }
Это правда, но зачем столько пустых методов?
Поднятие контекста, произойдет один раз и проверит все запросы, нам для этого не нужно создавать кучу пустых тестовых методов.

То есть в идеале это должно выглядеть как-то так:

```java
@DataJpaTest
class ItemRepositoryTest {
    @Test
    void contextLoads() {
    }
}
```

2024-06-01 07:58 UTC, LexLippi commented
Привет!

Хорошая работа!

Надо удалить лишние пустые методы из тестов и тогда все будет отлично!

Желаю удачи!

2024-06-01 08:04 UTC, vladbakushkin commented
Да, тоже пришел к выводу, что пустые тест методы ни к чему. Все проверки и так пройдут при поднятии контекста в тесте запуска приложения. Спасибо!

2024-06-01 08:48 UTC, vladbakushkin commented on src/test/java/ru/practicum/shareit/item/repository/ItemRepositoryTest.java
> +    }
Видимо, не так понял смысл этой проверки.
Поднятие контекста действительно происходит в тесте 
```java
@SpringBootTest
class ShareItTests {

    @Autowired
    private ApplicationContext applicationContext;

    @Test
    void contextLoads() {
        assertThat(applicationContext).isNotNull();
        assertDoesNotThrow(ShareItApp::new);
        assertDoesNotThrow(() -> ShareItApp.main(new String[]{}));
    }

}
```
И этого будет достаточно

2024-06-02 20:52 UTC, LexLippi commented
Привет!

Отличная работа!

Желаю удачи в следующих спринтах!

2024-06-03 17:10 UTC, merged